Repository aws-games/cloud-game-development-toolkit, pull requests merged in 2024-08, with the labels that each got.

#187 docs: Windows Build AMI README
  .chglog/config.yml
  CONTRIBUTING.md
  assets/packer/build-agents/windows/README.md
Labels: documentation

#190 ci: updating dependabot.yml
  .github/dependabot.yml
Labels: ci, dependencies

#193 fix: wait for cloud-init to complete prior to installing packages during Perforce Helix Core AMI creation
  assets/packer/perforce/helix-core/perforce.pkr.hcl
Labels: bug, packer, perforce

#194 docs: link to installation instructions for required tools, fix packer command invocation instructions
  assets/packer/perforce/helix-core/README.md
  docs/getting-started.md
Labels: documentation

#219 docs: add openssf scorecard badge to readme
  README.md
Labels: documentation

#228 fix: dependabot grouping terraform providers
  .github/dependabot.yml
Labels: ci
